##################
# UseCUDNN.cmake #
##################

OPTION(WITH_CUDNN "Build with CUDNN support?" ON)

IF(WITH_CUDNN AND WITH_CUDA)
	FIND_PACKAGE(CUDNN QUIET)
   
	INCLUDE_DIRECTORIES(${CUDNN_INCLUDE_DIR})
	ADD_DEFINITIONS(-DCOMPILE_WITH_CUDNN)
ENDIF()
