################
# UsePNG.cmake #
################

OPTION(WITH_PNG "Build with libpng support?" OFF)

IF(WITH_PNG)
	IF(MSVC_IDE)
		FIND_PACKAGE(Png REQUIRED)
	ELSE()
		FIND_PACKAGE(PNG REQUIRED)
	ENDIF()

	INCLUDE_DIRECTORIES(${PNG_INCLUDE_DIR})
	ADD_DEFINITIONS(${PNG_DEFINITIONS})
	ADD_DEFINITIONS(-DUSE_LIBPNG)
ENDIF()
